; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps =
	adafruit/Adafruit NeoPixel@^1.15.1
build_flags =
	-D LED_PIN=6
	-D LED_COUNT=8
	-D BRIGHTNESS=40

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps =
	adafruit/Adafruit NeoPixel@^1.15.1
build_flags =
	-D LED_PIN=6
	-D LED_COUNT=8
	-D BRIGHTNESS=40

[env:pico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
lib_deps =
	adafruit/Adafruit NeoPixel@^1.15.1
build_flags =
	-D LED_PIN=6
	-D LED_COUNT=4
	-D BRIGHTNESS=230
